"use client";
import { useEffect,useState,FormEvent } from "react";
import { ArrowRight,CheckCircle2,Eye,EyeOff,Lock,Mail,Loader2,Sparkles,BarChart3,Search,Users,ChevronDown } from "lucide-react";
import { supabase } from "@/lib/supabase";
import ThemeToggle from "./theme-toggle";

type Lang="pt-br"|"pt-pt"|"es"|"en";
const langs=[
 {id:"pt-br" as Lang,flag:"🇧🇷",label:"Português (Brasil)"},
 {id:"pt-pt" as Lang,flag:"🇵🇹",label:"Português (Portugal)"},
 {id:"es" as Lang,flag:"🇪🇸",label:"Español"},
 {id:"en" as Lang,flag:"🇺🇸",label:"English"},
];
const copy={
 "pt-br":{navFeatures:"Recursos",navPlans:"Planos",navFaq:"FAQ",sign:"Entrar",badge:"Seu laboratório de crescimento no YouTube",title:"Tudo o que você precisa para crescer. Sem sair do YouTube.",sub:"O TubeX coloca SEO, pesquisa, IA, análise e ferramentas para creators diretamente no seu fluxo de trabalho.",p1:"Dados para decidir o próximo vídeo",p2:"IA para criar e otimizar mais rápido",p3:"Ferramentas avançadas dentro do YouTube",welcome:"Bem-vindo de volta",access:"Acesse sua conta TubeX",email:"E-mail",password:"Senha",emailPh:"voce@exemplo.com",passPh:"Digite sua senha",forgot:"Esqueci minha senha",login:"Entrar",logging:"Entrando...",or:"ou continue com",google:"Continuar com Google",noAccount:"Ainda não tem uma conta?",create:"Criar conta",reset:"Enviamos um link para redefinir sua senha.",resetError:"Não foi possível enviar o link.",loginError:"E-mail ou senha incorretos.",googleError:"Não foi possível iniciar o Google.",free:"Comece grátis",why:"Por que creators escolhem o TubeX",whySub:"A extensão faz o trabalho dentro do YouTube. A área web fica leve: conta, assinatura, suporte e afiliados.",affiliate:"Programa de Afiliados",affiliateDesc:"Compartilhe o TubeX e acompanhe cliques, vendas e comissões em um só lugar.",pricing:"Planos",pricingSub:"Escolha o acesso que acompanha seu canal.",pro:"PRO",expert:"EXPERT",popular:"MAIS POPULAR",month:"/mês",annual:"/ano",annualSave:"Economize e pague menos no anual.",start:"Começar grátis",proBuy:"Assinar Pro",expertBuy:"Assinar Expert",faq:"Perguntas frequentes",q1:"O TubeX substitui a extensão?",a1:"Não. A extensão continua sendo o centro de trabalho no YouTube. Esta área web existe para conta, assinatura, afiliados e gestão.",q2:"Preciso pagar para começar?",a2:"Não. Você pode começar no plano Free e fazer upgrade quando precisar.",q3:"Posso usar mensal ou anual?",a3:"Sim. Pro e Expert possuem cobrança mensal e anual.",footer:"© 2026 TubeX. Todos os direitos reservados."},
 "pt-pt":{navFeatures:"Funcionalidades",navPlans:"Planos",navFaq:"FAQ",sign:"Entrar",badge:"O seu laboratório de crescimento no YouTube",title:"Tudo o que precisa para crescer. Sem sair do YouTube.",sub:"O TubeX coloca SEO, pesquisa, IA, análise e ferramentas para criadores diretamente no seu fluxo de trabalho.",p1:"Dados para decidir o próximo vídeo",p2:"IA para criar e otimizar mais depressa",p3:"Ferramentas avançadas dentro do YouTube",welcome:"Bem-vindo de volta",access:"Aceda à sua conta TubeX",email:"E-mail",password:"Palavra-passe",emailPh:"voce@exemplo.com",passPh:"Introduza a sua palavra-passe",forgot:"Esqueci-me da palavra-passe",login:"Entrar",logging:"A entrar...",or:"ou continue com",google:"Continuar com Google",noAccount:"Ainda não tem uma conta?",create:"Criar conta",reset:"Enviámos um link para redefinir a palavra-passe.",resetError:"Não foi possível enviar o link.",loginError:"E-mail ou palavra-passe incorretos.",googleError:"Não foi possível iniciar o Google.",free:"Começar gratuitamente",why:"Porque os criadores escolhem o TubeX",whySub:"A extensão faz o trabalho dentro do YouTube. A área web mantém-se leve: conta, subscrição, suporte e afiliados.",affiliate:"Programa de Afiliados",affiliateDesc:"Partilhe o TubeX e acompanhe cliques, vendas e comissões num só lugar.",pricing:"Planos",pricingSub:"Escolha o acesso adequado ao seu canal.",pro:"PRO",expert:"EXPERT",popular:"MAIS POPULAR",month:"/mês",annual:"/ano",annualSave:"Poupe no plano anual.",start:"Começar gratuitamente",proBuy:"Assinar Pro",expertBuy:"Assinar Expert",faq:"Perguntas frequentes",q1:"O TubeX substitui a extensão?",a1:"Não. A extensão continua a ser o centro de trabalho no YouTube. Esta área web existe para conta, subscrição, afiliados e gestão.",q2:"Preciso de pagar para começar?",a2:"Não. Pode começar no plano Free e fazer upgrade quando precisar.",q3:"Posso usar mensal ou anual?",a3:"Sim. Pro e Expert têm cobrança mensal e anual.",footer:"© 2026 TubeX. Todos os direitos reservados."},
 "es":{navFeatures:"Funciones",navPlans:"Planes",navFaq:"FAQ",sign:"Iniciar sesión",badge:"Tu laboratorio de crecimiento en YouTube",title:"Todo lo que necesitas para crecer. Sin salir de YouTube.",sub:"TubeX pone SEO, investigación, IA, análisis y herramientas para creadores directamente en tu flujo de trabajo.",p1:"Datos para decidir tu próximo vídeo",p2:"IA para crear y optimizar más rápido",p3:"Herramientas avanzadas dentro de YouTube",welcome:"Bienvenido de nuevo",access:"Accede a tu cuenta TubeX",email:"Correo",password:"Contraseña",emailPh:"tu@ejemplo.com",passPh:"Introduce tu contraseña",forgot:"Olvidé mi contraseña",login:"Iniciar sesión",logging:"Iniciando sesión...",or:"o continúa con",google:"Continuar con Google",noAccount:"¿Aún no tienes una cuenta?",create:"Crear cuenta",reset:"Te enviamos un enlace para restablecer tu contraseña.",resetError:"No se pudo enviar el enlace.",loginError:"Correo o contraseña incorrectos.",googleError:"No se pudo iniciar Google.",free:"Empezar gratis",why:"Por qué los creadores eligen TubeX",whySub:"La extensión hace el trabajo dentro de YouTube. La web se mantiene ligera: cuenta, suscripción, soporte y afiliados.",affiliate:"Programa de Afiliados",affiliateDesc:"Comparte TubeX y controla clics, ventas y comisiones en un solo lugar.",pricing:"Planes",pricingSub:"Elige el acceso adecuado para tu canal.",pro:"PRO",expert:"EXPERT",popular:"MÁS POPULAR",month:"/mes",annual:"/año",annualSave:"Ahorra con el plan anual.",start:"Empezar gratis",proBuy:"Suscribirse a Pro",expertBuy:"Suscribirse a Expert",faq:"Preguntas frecuentes",q1:"¿TubeX sustituye la extensión?",a1:"No. La extensión sigue siendo el centro de trabajo dentro de YouTube. Esta web existe para cuenta, suscripción, afiliados y gestión.",q2:"¿Tengo que pagar para empezar?",a2:"No. Puedes empezar con el plan Free y actualizar cuando lo necesites.",q3:"¿Puedo elegir mensual o anual?",a3:"Sí. Pro y Expert tienen facturación mensual y anual.",footer:"© 2026 TubeX. Todos los derechos reservados."},
 "en":{navFeatures:"Features",navPlans:"Pricing",navFaq:"FAQ",sign:"Sign in",badge:"Your YouTube growth lab",title:"Everything you need to grow. Without leaving YouTube.",sub:"TubeX brings SEO, research, AI, analytics and creator tools directly into your workflow.",p1:"Data to decide what to publish next",p2:"AI to create and optimize faster",p3:"Advanced tools inside YouTube",welcome:"Welcome back",access:"Access your TubeX account",email:"Email",password:"Password",emailPh:"you@example.com",passPh:"Enter your password",forgot:"Forgot password?",login:"Sign in",logging:"Signing in...",or:"or continue with",google:"Continue with Google",noAccount:"Don't have an account yet?",create:"Create account",reset:"We sent you a password reset link.",resetError:"We couldn't send the reset link.",loginError:"Invalid email or password.",googleError:"We couldn't start Google sign-in.",free:"Start for free",why:"Why creators choose TubeX",whySub:"The extension does the work inside YouTube. The web stays focused: account, billing, support and affiliates.",affiliate:"Affiliate Program",affiliateDesc:"Share TubeX and track clicks, sales and commissions in one place.",pricing:"Plans",pricingSub:"Choose the access that fits your channel.",pro:"PRO",expert:"EXPERT",popular:"MOST POPULAR",month:"/month",annual:"/year",annualSave:"Save with annual billing.",start:"Start for free",proBuy:"Subscribe to Pro",expertBuy:"Subscribe to Expert",faq:"Frequently asked questions",q1:"Does TubeX replace the extension?",a1:"No. The extension remains the main workspace inside YouTube. The web area focuses on account, billing, affiliates and management.",q2:"Do I need to pay to start?",a2:"No. Start with the Free plan and upgrade when you need more.",q3:"Can I choose monthly or annual?",a3:"Yes. Pro and Expert are available monthly and annually.",footer:"© 2026 TubeX. All rights reserved."}
} as const;

function Logo(){return <a href="/" className="flex items-center gap-2 font-black tracking-[-.06em] text-[23px] text-[var(--tx-text)]"><span className="grid h-8 w-8 place-items-center rounded-[10px] bg-[var(--tx-accent)] text-[11px] font-black text-[#10151d]">TX</span>Tube<span className="text-[var(--tx-accent)]">X</span></a>}

export default function LoginPage(){
 const [lang,setLang]=useState<Lang>("pt-br"),[openLang,setOpenLang]=useState(false),[affiliateRef,setAffiliateRef]=useState("");
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false);
 const [loading,setLoading]=useState(false),[googleLoading,setGoogleLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{
  const saved=localStorage.getItem("tubex-language") as Lang|null;
  const b=navigator.language.toLowerCase();
  const l=saved||(b.startsWith("pt-br")?"pt-br":b.startsWith("pt")?"pt-pt":b.startsWith("es")?"es":"en");
  setLang(l);document.documentElement.lang=l;
  const ref=(localStorage.getItem("affiliate_ref")||"").trim().toUpperCase();
  setAffiliateRef(ref);
},[]);
 const t=copy[lang];
 function checkoutUrl(base:string){
   if(!affiliateRef) return base;
   return `${base}${base.includes("?")?"&":"?"}client_reference_id=${encodeURIComponent(affiliateRef)}`;
 }
 function changeLang(l:Lang){setLang(l);setOpenLang(false);localStorage.setItem("tubex-language",l);document.documentElement.lang=l;window.dispatchEvent(new CustomEvent("tubex-language-change",{detail:l}))}
 async function login(e:FormEvent){e.preventDefault();setLoading(true);setError("");const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)setError(t.loginError);else window.location.href="/dashboard";setLoading(false)}
 async function google(){setGoogleLoading(true);const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/dashboard`,scopes:"openid email profile https://www.googleapis.com/auth/youtube.readonly",queryParams:{access_type:"offline",prompt:"consent"}}});if(error){setError(t.googleError);setGoogleLoading(false)}}
 async function reset(){if(!email.trim()){setError(t.email+" obrigatório");return}setLoading(true);const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/reset-password`});if(error)setError(t.resetError);else setMessage(t.reset);setLoading(false)}
 const feature=[{i:<Search size={18}/>,t:t.p1},{i:<Sparkles size={18}/>,t:t.p2},{i:<BarChart3 size={18}/>,t:t.p3}];
 return <main className="min-h-screen bg-[var(--tx-bg)] text-[var(--tx-text)]">
  <header className="sticky top-0 z-40 border-b border-[var(--tx-border)] bg-[var(--tx-bg)]/90 backdrop-blur-xl">
   <div className="mx-auto flex h-[68px] w-[min(1180px,calc(100%-28px))] items-center gap-4">
    <Logo/><nav className="ml-auto hidden gap-1 md:flex"><a href="#recursos" className="tx-nav">Recursos</a><a href="#planos" className="tx-nav">{t.navPlans}</a><a href="#faq" className="tx-nav">{t.navFaq}</a></nav>
    <ThemeToggle/><div className="relative"><button onClick={()=>setOpenLang(!openLang)} className="tx-mini-btn">{langs.find(x=>x.id===lang)?.flag} <span>{lang.toUpperCase()}</span><ChevronDown size={12}/></button>{openLang&&<div className="tx-menu">{langs.map(x=><button key={x.id} onClick={()=>changeLang(x.id)}>{x.flag} {x.label}</button>)}</div>}</div>
    <a href="#login" className="tx-btn tx-btn-primary">{t.sign}</a>
   </div>
  </header>
  <section className="mx-auto grid w-[min(1180px,calc(100%-28px))] gap-12 py-14 lg:grid-cols-[1fr_450px] lg:items-center lg:py-20">
   <div>
    <div className="tx-eyebrow"><Sparkles size={13}/>{t.badge}</div>
    <h1 className="mt-6 max-w-3xl text-5xl font-black leading-[.98] tracking-[-.06em] sm:text-6xl">{t.title}</h1>
    <p className="mt-6 max-w-2xl text-base leading-7 text-[var(--tx-muted)]">{t.sub}</p>
    <div className="mt-8 grid gap-3">{[t.p1,t.p2,t.p3].map(x=><div key={x} className="flex items-center gap-3 text-sm font-semibold"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[var(--tx-accent-soft)] text-[var(--tx-accent)]"><CheckCircle2 size={15}/></span>{x}</div>)}</div>
    <div className="mt-9 flex flex-wrap gap-3"><a href="#planos" className="tx-btn tx-btn-primary">{t.free}<ArrowRight size={15}/></a><a href="#recursos" className="tx-btn tx-btn-secondary">Explore TubeX</a></div>
   </div>
   <div id="login" className="tx-login-card tx-surface scroll-mt-24">
    <div className="flex items-start justify-between"><div><p className="tx-kicker">TUBEX ACCOUNT</p><h2 className="mt-2 text-2xl font-black">{t.welcome}</h2><p className="mt-1 text-sm text-[var(--tx-muted)]">{t.access}</p></div><Lock size={18} className="text-[var(--tx-accent)]"/></div>
    {message&&<div className="tx-success">{message}</div>}{error&&<div className="tx-error">{error}</div>}
    <form onSubmit={login} className="mt-6 grid gap-4">
      <label className="grid gap-2"><span className="tx-label">{t.email}</span><div className="tx-input-wrap"><Mail size={16}/><input className="tx-input" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder={t.emailPh}/></div></label>
      <label className="grid gap-2"><span className="tx-label">{t.password}</span><div className="tx-input-wrap"><Lock size={16}/><input className="tx-input" type={show?"text":"password"} required value={password} onChange={e=>setPassword(e.target.value)} placeholder={t.passPh}/><button type="button" className="text-[var(--tx-muted)]" onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></label>
      <button type="button" onClick={reset} className="justify-self-end text-xs font-bold text-[var(--tx-accent)]">{t.forgot}</button>
      <button disabled={loading} className="tx-btn tx-btn-primary w-full">{loading?<Loader2 className="animate-spin" size={16}/>:t.login}</button>
    </form>
    <div className="my-5 flex items-center gap-3 text-[10px] text-[var(--tx-muted)]"><span className="h-px flex-1 bg-[var(--tx-border)]"/>{t.or}<span className="h-px flex-1 bg-[var(--tx-border)]"/></div>
    <button disabled={googleLoading} onClick={google} className="tx-btn tx-btn-secondary w-full justify-center">{googleLoading?<Loader2 className="animate-spin" size={16}/>:<><span className="grid h-5 w-5 place-items-center rounded-full bg-white text-xs font-black text-[#4285F4]">G</span>{t.google}</>}</button>
    <p className="mt-5 text-center text-xs text-[var(--tx-muted)]">{t.noAccount} <a href="/signup" className="font-bold text-[var(--tx-accent)]">{t.create}</a></p>
   </div>
  </section>
  <section id="recursos" className="border-y border-[var(--tx-border)] bg-[var(--tx-surface)] py-20"><div className="mx-auto w-[min(1180px,calc(100%-28px))]"><div className="max-w-2xl"><p className="tx-kicker">{t.why}</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em]">{t.whySub}</h2></div><div className="mt-9 grid gap-4 md:grid-cols-3">{feature.map((x,i)=><div key={i} className="tx-feature"><div className="tx-feature-icon">{x.i}</div><h3 className="mt-5 font-black">{x.t}</h3><p className="mt-2 text-sm leading-6 text-[var(--tx-muted)]">{i===0?"Keyword Explorer, SEO e sinais de demanda.":i===1?"IA, títulos, descrições e scripts.":"Métricas e decisões para entender o canal."}</p></div>)}</div></div></section>
  <section id="planos" className="py-20"><div className="mx-auto w-[min(1180px,calc(100%-28px))]"><div className="text-center"><p className="tx-kicker">{t.pricing}</p><h2 className="mt-3 text-4xl font-black tracking-[-.05em]">{t.pricingSub}</h2></div><div className="mt-10 grid gap-5 lg:grid-cols-3">
   <div className="tx-plan"><p className="tx-kicker">FREE</p><h3 className="mt-2 text-xl font-black">R$0</h3><p className="mt-2 text-sm text-[var(--tx-muted)]">Para experimentar o TubeX.</p><ul className="mt-6 grid gap-3 text-sm">{["5 análises SEO/dia","10 consultas Summary","Acesso inicial"].map(x=><li key={x}>✓ {x}</li>)}</ul><a href="https://chromewebstore.google.com/detail/tubex-seo-analyzer-for-yo/lgddmmhnmkmkfhaodogcoecdecegemgk" target="_blank" rel="noreferrer" className="tx-btn tx-btn-secondary mt-7 w-full justify-center">{t.start}</a></div>
   <div className="tx-plan"><p className="tx-kicker">{t.pro}</p><h3 className="mt-2 text-3xl font-black">R$29,99 <small className="text-sm font-semibold text-[var(--tx-muted)]">{t.month}</small></h3><ul className="mt-6 grid gap-3 text-sm"><li>✓ 50 análises SEO/dia</li><li>✓ SEO, IA, Tendências e Tags</li><li>✓ Ferramentas avançadas</li></ul><div className="tx-annual">R$299,90 {t.annual}<span>{t.annualSave}</span></div><a href={checkoutUrl("https://buy.stripe.com/3cI7sK7058OtdzDaUegjC01")} target="_blank" rel="noreferrer" className="tx-btn tx-btn-primary mt-4 w-full justify-center">{t.proBuy}</a><a href={checkoutUrl("https://buy.stripe.com/28E3cudote8NgLPd2mgjC03")} target="_blank" rel="noreferrer" className="tx-btn tx-btn-secondary mt-2 w-full justify-center">Pro {t.annual}</a></div>
   <div className="tx-plan tx-plan-pop"><span className="tx-pop">{t.popular}</span><p className="tx-kicker">{t.expert}</p><h3 className="mt-2 text-3xl font-black">R$49,99 <small className="text-sm font-semibold text-[var(--tx-muted)]">{t.month}</small></h3><ul className="mt-6 grid gap-3 text-sm"><li>✓ SEO ilimitado</li><li>✓ Creator Workspace</li><li>✓ IA avançada</li><li>✓ Acesso antecipado</li><li>✓ Afiliados</li></ul><div className="tx-annual">R$499,90 {t.annual}<span>{t.annualSave}</span></div><a href={checkoutUrl("https://buy.stripe.com/dRmaEW98dggV3Z3d2mgjC02")} target="_blank" rel="noreferrer" className="tx-btn tx-btn-primary mt-4 w-full justify-center">{t.expertBuy}</a><a href={checkoutUrl("https://buy.stripe.com/28E8wO3NTe8N67b2nIgjC04")} target="_blank" rel="noreferrer" className="tx-btn tx-btn-secondary mt-2 w-full justify-center">Expert {t.annual}</a></div>
  </div></div></section>
  <section id="faq" className="border-t border-[var(--tx-border)] bg-[var(--tx-surface)] py-20"><div className="mx-auto w-[min(850px,calc(100%-28px))]"><p className="tx-kicker">{t.faq}</p><div className="mt-6 grid gap-3">{[[t.q1,t.a1],[t.q2,t.a2],[t.q3,t.a3]].map(([q,a])=><details key={q} className="tx-faq"><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
  <footer className="border-t border-[var(--tx-border)] py-7 text-center text-xs text-[var(--tx-muted)]">{t.footer} · <a href="/privacy">Privacidade</a> · <a href="/terms">Termos</a></footer>
 </main>
}